
nacos:
  config:
    endpoint:
    namespace:
    access-key: 
    secret-key: 


# redis配置
spring:
  redis:
    database: 0
    host:
    port:
    password:

# 日志
logging:
  level:
    org.ccccye.weather.aop: debug
    org.ccccye.weather.controller: debug
    org.ccccye.weather.feign: debug
  file: ./log/local.log
