server:
  port: 7020

spring:
  application:
    name: source
  redis:
    # 数据库索引
    database: 0
    # 服务地址
    host: 47.106.122.7
    # 服务端口
    port: 6379
    # 连接密钥
    password:
    # 超时（毫秒）
    timeout: 3000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

logging:
  level:
    root: info

weather:
  type: he
  he:
    key: e914aa68a5c943bb8d96504b33ce0157

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://47.106.122.7:7001/eureka