server:
  port: 9500

spring:
  application:
    name: wx

weather:
  he:
    key: abcd

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true