server:
  port: 7010

spring:
  application:
    name: wx

weather:
  he:
    key:

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    prefer-ip-address: true