server:
  port: 7010

spring:
  application:
    name: wx

eureka:
  client:
    service-url:
      defaultZone: http://47.106.122.7:7001/eureka/
  instance:
#    prefer-ip-address: true
    instance-id: http://2455r6l881.qicp.vip/

logging:
  level:
    org.ccccye.weather.api.wx.api: debug